server:
  port: ${port:10086}
spring:
  application:
    name: eureka-server01
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: ${defaultZone:http://127.0.0.1:10087/eureka}
