server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  freemarker:
    cache: false # close cache
    settings:
      template_update_delay: 0
