server:
  port: ${port:31001}
spring:
  application:
    name: XcServiceManageCms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  freemarker:
    cache: false # close cache
    settings:
      template_update_delay: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:50101/eureka, http://localhost:50102/eureka

