server:
  port: 10087
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:10087/erueka
spring:
  application:
    name: eureka-service02